language: node_js
node_js:
- stable
- '6'
- '4'
deploy:
  provider: npm
  on:
    tags: true
  api_key:
    secure: Ml/o3KzAtNy9VXvQA2TMKnaPhmLdu02VxjxGHXqlZlYLLjkUZ50/6pl/cYRefdRx/r5ot6HlNrLeZdTqYLSIDN9FNO9xIfPjhZhHCd7YFRbRRMKyGe8/SsbQEe3CHXxyZ2XlJYaL2uT72xgIykw4berTZdeHlFJUhUwQlt3xRrKXJ6Poh2IvQBYHESKjmi3g2farZTeK27TGxs41EScAKoY4y7WtOrh6cMiO/UDDSsPNsdOstJKK8QqMmVkv+dBJ8Tt6pLd9zS4flt2roB25nbU7nmKwaKPEM22ewFQ2+NGeozr9m/S4lE1tKJNXxgJ2ugKfzDiCyfrh5DVQVlQqG5VHZreSDsGdjDDRO8o61jMth5OhpCOlccdBbrZUXKgj8KKmzVqR5Q0x4kumqQHindwgJF/mtTFlV12zBRxL02D9lvmvEeJhRZR0fFmxrOgRDz1BXdcwLIRTasNxCjguK3PV34z6/On6DvIHnO1fvtupHGIiCrSX6Zphc5oDPl4Wm0892WubRN15wwIbdqanf3BWjW90wns+wzRGoQqHCnOWgteCdF/8lksLkLKqviaBxq+wsLOwK5tbrUxcK0yMcVEnHr2ljpKUWiYAOSo8WO+FqMsTjVJqefnhervtK9jia88mHqEV/Nb28Q5oYjIjT0NGav2Iy0P9qeoV6i648vU=
